# Makefile

CXX = g++
CXXFLAGS = -std=c++11

encoder:
	$(CXX) $(CXXFLAGS) brrencoder.cpp -o brrencoder

decoder:
	$(CXX) $(CXXFLAGS) brrdecoder.cpp -o brrdecoder

analyzer:
	$(CXX) $(CXXFLAGS) psnranalyzer.cpp -o psnranalyzer
