# Makefile

CXX = g++
CXXFLAGS = -std=c++11

encoder:
	$(CXX) $(CXXFLAGS) brrencoder.cpp -o encoder.exe

decoder:
	$(CXX) $(CXXFLAGS) brrdecoder.cpp -o decoder.exe

analyzer:
	$(CXX) $(CXXFLAGS) psnranalyzer.cpp -o analyzer.exe
